name: FoxPets
version: '${project.version}'
main: com.reflexian.foxsmp.FoxSMP
api-version: 1.20
depend:
  - ProtocolLib
#  - CommandAPI
#  - ItemsAdder
#  - SmartInvs
  - WorldGuard
  - PlaceholderAPI
authors: [Raymond, Whale]
website: reflexian.com
