name: FoxSMP
version: '${project.version}'
main: com.reflexian.foxsmp.FoxSMP
api-version: '1.20'
depend:
  - ProtocolLib
#  - CommandAPI
  - helper
#  - ItemsAdder
#  - SmartInvs
  - WorldGuard
authors: [Raymond, Whale]
website: reflexian.com
